### ISSUE TITLE
Sketch a UI

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/did-spike#1]

**Comment by GinoCanessa** [comment]
![20191014-DID-Spike-UI](https://user-images.githubusercontent.com/50417653/66786700-eb3aec80-eea6-11e9-839a-3cef2606554f.png)

**Comment by jmandel** [comment]
Let's use these as a rough target for the UI. Sorry for the illegible handwriting. By screen these say:

1. Welcome! Huh? [Make a did]
2. Connect to Healthcare [Provider]. [Connect]
3. Your account: ___ name, ___dob, ___ addr, ___ [phone-icon] [check], [Create Verified Credential]
4. Wait for SMS [enter-numbers], [Enter Code]
5. Your Credential: [credential-details], [Save]
