### ISSUE TITLE
More standard VC schema

### ISSUE THREAD

**Issue by davux** [microsoft-healthcare-madison/did-spike#13]
From [this example](https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/master/src/fixtures/vc.json), it looks like the JSON schema could be improved to better match existing credential schemas.

One possible improvement is to keep in mind that `credentialSubject` is the subject of the credential. For a vaccine credential, that's the patient. So semantically, any attribute in `credentialSubject` is to be read as an attribute of the patient: name, etc. However it looks like the `credentialSubject` object in the example is not structured this way.

Second, the choice of attribute names should match common practice. One good reference is https://schema.org. For example `givenName` and `familyName` should be used rather than `given` and `family`.

It's excellent that such a bridge between FHIR and VC is sought. I hope we do things well and stay as standard as possible at every level, not only with FHIR.

**Comment by jmandel** [comment]
Quick note that this repo was created for a one-week "spike" (exploratory project) in late 2019; it's not reflecting ongoing work.

**Comment by davux** [comment]
Thanks @jmandel! Where is the credential schema definition happening?

**Comment by jmandel** [comment]
In this project, credential schema definition was essential implicit (https://github.com/microsoft-healthcare-madison/did-spike/blob/master/issuer/data/vc_01.json#L11-L25 has an example). The goal of this repo was just to test the idea of sharing info like "User X has access to Resource Y in System Z".

**Comment by jmandel** [comment]
I'm going to archive this repo to reflect the fact there's no ongoing development here, but you may want to check out [SMART Health Cards](https://healthwallet.cards) for the logical continuation.
